#ifndef APPLICATION_CONFIG_H
#define APPLICATION_CONFIG_H

#define APPLICATION_ADC_LED_ON_THRESHOLD_MV  (1800U)
#define APPLICATION_ADC_LED_OFF_THRESHOLD_MV (1500U)

#if APPLICATION_ADC_LED_OFF_THRESHOLD_MV >= \
    APPLICATION_ADC_LED_ON_THRESHOLD_MV
#error "ADC LED off threshold must be below on threshold."
#endif

#endif
