#ifndef APPLICATION_CONFIG_H
#define APPLICATION_CONFIG_H

#define APPLICATION_PWM_UPDATE_PERIOD_MS  (10UL)
#define APPLICATION_PWM_STEP_PERMILLE     (10U)

#if APPLICATION_PWM_UPDATE_PERIOD_MS == 0UL
#error "APPLICATION_PWM_UPDATE_PERIOD_MS must be non-zero."
#endif

#if (APPLICATION_PWM_STEP_PERMILLE == 0U) || \
    (APPLICATION_PWM_STEP_PERMILLE > 1000U)
#error "APPLICATION_PWM_STEP_PERMILLE must be in the range 1..1000."
#endif

#endif
