#ifndef BOARD_PINS_H
#define BOARD_PINS_H

#include "mcal_gpio.h"

#define BOARD_STATUS_LED_PORT         MCAL_GPIO_PORT_C
#define BOARD_STATUS_LED_PIN          (13U)
#define BOARD_STATUS_LED_ACTIVE_LEVEL MCAL_GPIO_LEVEL_LOW

#define BOARD_USER_BUTTON_PORT         MCAL_GPIO_PORT_A
#define BOARD_USER_BUTTON_PIN          (0U)
#define BOARD_USER_BUTTON_ACTIVE_LEVEL MCAL_GPIO_LEVEL_LOW
#define BOARD_USER_BUTTON_EXTI_LINE    (0U)
#define BOARD_USER_BUTTON_IRQ_PRIORITY (2U)

#endif
